services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - transcendence
    volumes:
      - ${VOLUME_PATH}/postgres_data:/var/lib/posgresql/data
    env_file:
      - .env
    user: "999:999"

  django:
    build: ./srcs/django
    container_name: django
    networks:
      - transcendence
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./srcs/django/django_app:/app
      - ${VOLUME_PATH}/media_data:/media
    env_file:
      - .env

  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./srcs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./srcs/nginx/content:/usr/share/nginx/html:ro
      - ./srcs/nginx/ssl:/etc/nginx/ssl:ro
      - ${VOLUME_PATH}/media_data:/media:ro
    networks:
      - transcendence
    depends_on:
      - django

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/postgres_data
  media_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/media_data

networks:
  transcendence:
    name: transcendence
