services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - transcendence
    volumes:
      - postgres_data:/var/lib/posgresql/data
    env_file:
      - .env

  django:
    build: ./srcs/django
    container_name: django
    ports:
      - "8000:8000"
    networks:
      - transcendence
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./srcs/django/django_app:/app
    env_file:
      - .env

  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./srcs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./srcs/nginx/content:/usr/share/nginx/html
    networks:
      - transcendence
    volumes:
      - ./srcs/nginx/content:/usr/share/nginx/html

volumes:
  postgres_data:

networks:
  transcendence:
    name: transcendence
