# Generated by Django 5.1.3 on 2025-03-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchhistory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchhistory',
            old_name='game_id',
            new_name='id',
        ),
    ]
