# Generated by Django 5.1.3 on 2025-03-28 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_friends_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='is_blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='is_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
