# Generated by Django 5.1.3 on 2025-03-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_blocked_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
    ]
