# Generated by Django 5.1.3 on 2025-04-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='auth_token_42',
        ),
        migrations.AddField(
            model_name='user',
            name='password_set',
            field=models.BooleanField(default=False),
        ),
    ]
