# Generated by Django 5.1.3 on 2025-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_42',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
